# Generated by Django 4.2.7 on 2023-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_options_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(),
        ),
    ]
